[aliases]
"video" =                  "\uf1c8"
"audio" =                  "\uf1c7"
"book"  =                  "\uf02d"
"eslint" =                 "\ue655"
"prettier" =               "\ue6b4"
"image" =                  "\uf1c5"
"ruby" =                   "\ue21e"
"license" =                "\uf24e"
"db" =                     "\uf1c0"
"dotenv" =                 "\uf456"
"compress" =               "\uf410"
"package" =                "\uf487"
"docker" =                 "\uf308"
"font" =                   "\uf031"
"javascript" =             "\ue74e"
"android" =                "\ue70e"
"apple" =                  "\uf179"
"shell" =                  "\uf489"
"git_file" =               "\uf1d3"
"vim" =                    "\ue62b"
"rails" =                  "\ue604"
"yarn" =                   "\ue6a7"
"safari" =                 "\ue748"
"golang" =                 "\ue65e"
"config" =                 "\ue615"
"text" =                   "\uf0f6"

[files]
# golang
".go" =                    "golang"
"go.mod" =                 "golang"
"go.sum" =                 "golang"
"go.list" =                "golang"

# vim
".vim" =                   "vim"
".viminfo" =               "vim"
".vimrc" =                 "vim"

# git
".gitattributes" =         "git_file"
".gitignore" =             "git_file"
".gitconfig" =             "git_file"

# javascript
".js" =                    "javascript"
".mjs" =                   "javascript"
".cjs" =                   "javascript"

# font
".eot" =                   "font"
".otf" =                   "font"
".ttf" =                   "font"
".woff" =                  "font"
".woff2" =                 "font"

# docker
".dockerignore" =          "docker"
"Dockerfile" =             "docker"

# compress/packages
".7z" =                    "compress"
".dmg" =                   "package"
".iso" =                   "package"
".pkg" =                   "package"
".gz" =                    "compress"
".tar" =                   "compress"
".xip" =                   "compress"
".zip" =                   "compress"
".rar" =                   "compress"
".tgz" =                   "compress"
".xz" =                    "compress"

# dotenv
".env" =                   "dotenv"
".env.development" =       "dotenv"
".env.local" =             "dotenv"
".env.production" =        "dotenv"
".env.test" =              "dotenv"
".env.example" =           "dotenv"
".env.sample" =            "dotenv"

# readme
"README" =                 "book"
"README.md" =              "book"
"README.txt" =             "book"

# database
".database" =              "db"
".db" =                    "db"
".dump" =                  "db"
".prql" =                  "db"
".psql" =                  "db"
".sql" =                   "db"
".sqlite" =                "db"
".sqlite3" =               "db"

# ruby
".gemspec" =               "ruby"
".rake" =                  "ruby"
".rb" =                    "ruby"
".rubydoc" =               "ruby"
".ru" =                    "ruby"
"Gemfile" =                "ruby"
"Guardfile" =              "ruby"
"Podfile" =                "ruby"
"Rakefile" =               "ruby"
"Vagrantfile" =            "ruby"

# license
"LICENSE" =                "license"
"LICENSE.md" =             "license"
"LICENSE.txt" =            "license"
"MIT-LICENSE" =            "license"

# image
".avif" =                  "image"
".bmp" =                   "image"
".eps" =                   "image"
".gif" =                   "image"
".heif" =                  "image"
".ico" =                   "image"
".jpeg" =                  "image"
".jpg" =                   "image"
".jxl" =                   "image"
".odg" =                   "image"
".png" =                   "image"
".pxm" =                   "image"
".svg" =                   "image"
".tiff" =                  "image"
".webp" =                  "image"

# prettier
".prettierrc" =            "prettier"
".prettierrc.cjs" =        "prettier"
".prettierrc.js" =         "prettier"
".prettierrc.json" =       "prettier"
".prettierrc.json5" =      "prettier"
".prettierrc.mjs" =        "prettier"
".prettierrc.toml"    =    "prettier"
".prettierrc.yaml" =       "prettier"
".prettierrc.yml" =        "prettier"
"prettier.config.cjs" =    "prettier"
"prettier.config.js" =     "prettier"
"prettier.config.mjs" =    "prettier"

# eslint
".eslintrc.cjs" =          "eslint"
".eslintrc.js" =           "eslint"
".eslintrc.json" =         "eslint"
".eslintrc.yaml" =         "eslint"
".eslintrc.yml" =          "eslint"
"eslint.config.cjs" =      "eslint"
"eslint.config.cts" =      "eslint"
"eslint.config.js" =       "eslint"
"eslint.config.mjs" =      "eslint"
"eslint.config.mts" =      "eslint"
"eslint.config.ts" =       "eslint"

# audio
".aif" =                   "audio"
".aiff" =                  "audio"
".flac" =                  "audio"
".m4a" =                   "audio"
".mp3" =                   "audio"
".wav" =                   "audio"

# video
".avi" =                   "video"
".flv" =                   "video"
".mkv" =                   "video"
".mov" =                   "video"
".mp4" =                   "video"
".ogv" =                   "video"
".webm" =                  "video"

# ebooks
".epub" =                  "book"
".kfx" =                   "book"
".mobi" =                  "book"
".azw" =                   "book"
".azw3" =                  "book"
".iba" =                   "book"

# shell
".bash" =                  "shell"
".bashrc" =                "shell"
"bashrc" =                 "shell"
".sh" =                    "shell"
".shell" =                 "shell"
".zsh" =                   "shell"
".fish" =                  "shell"
".fishrc" =                "shell"
".fish_history" =          "shell"
".zshrc" =                 "shell"
"zshrc" =                  "shell"
".zshenv" =                "shell"
".zsh_history" =           "shell"
".bash_history" =          "shell"

# config
".cnf" =                   "config"
".conf" =                  "config"
".ini" =                   "config"

# text
".log" =                   "text"
".txt" =                   "text"
".rst" =                   "text"

# everything else
".ai" =                    "\ue7b4"
".apk" =                   "android"
".avro" =                  "\ue60b"
".bin" =                   "\ueae8"
".c" =                     "\ue61e"
".clj" =                   "\ue768"
".coffee" =                "\uf0f4"
".cpp" =                   "\ue61d"
".crx" =                   "\uf268"
".css" =                   "\ue614"
".csv" =                   "\ueefc"
".d" =                     "\ue7af"
".dart" =                  "\ue798"
".diff" =                  "\uf440"
".doc" =                   "\uf1c2"
".docx" =                  "\uf1c2"
".eml" =                   "\ueb1c"
".erl" =                   "\ue7b1"
".ex" =                    "\ue62d"
".exs" =                   "\ue62d"
".firebaserc" =            "\ue657"
".font" =                  "\uf031"
".gem" =                   "\ue739"
".hs" =                    "\ue777"
".html" =                  "\ue60e"
".icc" =                   "\ueb5c"
".ics" =                   "\uf274"
".iml" =                   "\ue735"
".java" =                  "\ue66d"
".json" =                  "\ue60b"
".jsx" =                   "\ue7ba"
".key" =                   "\uf456"
".less" =                  "\ue758"
".lhs" =                   "\ue777"
".lock" =                  "\uf456"
".lua" =                   "\ue620"
".md" =                    "\uf48a"
".mustache" =              "\ue60f"
".nix" =                   "\uf313"
".npmignore" =             "\ue71e"
".npmrc" =                 "\ue71e"
".patch" =                 "\uf440"
".pdf" =                   "\uf1c1"
".php" =                   "\ue73d"
".pl" =                    "\ue769"
".plist" =                 "\ueb86"
".ppt" =                   "\uf1c4"
".psd" =                   "\ue67f"
".py" =                    "\ue606"
".r" =                     "\uf15d"
".railsrc" =               "rails"
".rdb" =                   "\ue76d"
".react" =                 "\uf41a"
".rs" =                    "\ue7a8"
".rss" =                   "\uf09e"
".safariextz" =            "safari"
".sass" =                  "\ue603"
".scala" =                 "\ue737"
".sock" =                  "\uf44c"
".socket" =                "\uf44c"
".styl" =                  "\ue600"
".sublime-project" =       "\ue7aa"
".sublime-workspace" =     "\ue7aa"
".swift" =                 "\ue699"
".tex" =                   "\ue600"
".toml" =                  "\ue6b2"
".tool-versions" =         "\uf454"
".ts" =                    "\ue628"
".tsx" =                   "\ue7ba"
".twig" =                  "\ue61c"
".vue" =                   "\uf802"
".wasm" =                  "\ue6a1"
".windows" =               "\uf17a"
".xls" =                   "\uf1c3"
".xlsx" =                  "\uf1c3"
".xml" =                   "\ue60e"
".yaml" =                  "\ue6a8"
".yarnrc" =                "yarn"
".yarnrc.yaml" =           "yarn"
".yarnrc.yml" =            "yarn"
".yml" =                   "\ue6a8"
"AndroidManifest.xml" =    "android"
"Brewfile" =               "\uf0fc"
"file" =                   "\uf4a5"
"gruntfile.js" =           "\ue74c"
"Makefile" =               "\ue673"
"nginx.conf"             = "\ue776"
"package-lock.json" =      "\uf456"
"package.json" =           "\ue71e"
"Procfile" =               "\ueba2"
"Procfile.dev" =           "\ueba2"
"react-native.config.js" = "\ue625"
"tsconfig.json" =          "\ue628"

[folders]
".app" =             "\uf0bd"
".atom" =            "\ue764"
".git" =             "\ue5fb"
".github" =          "\ue5fd"
".key" =             "\uf1c4"
".npm" =             "\ue5fa"
".rvm" =             "\ue21e"
".Trash" =           "\uf1f8"
".vim" =             "vim"
".yarn" =            "yarn"
".vscode" =          "\ue70c"
".vscode-insiders" = "\ue70c"
".safariextension" = "safari"
"android" =          "android"
"bin" =              "\ue5fc"
"config" =           "\ue5fc"
"folder" =           "\ue5ff"
"hidden" =           "\uf023"
"include" =          "\ue5fc"
"ios" =              "apple"
"node_modules" =     "\ue5fa"
"open_folder" =      "\ue5fe"

[colors]
"file" =             "magenta"
"executable_file" =  "green"
"dir" =              "blue"
"dead_link" =        "red"
"link" =             "cyan"
"file_size" =        "white"
"hidden" =           "yellow"
"hidden_dir" =       "yellow"
